spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/todosync
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    org.flywaydb: DEBUG